Bugfixes UserController
OlhenShu/GreenCityUserMVPTemplate pull request #14
Opened 2023-12-21 12:07 UTC by KizerovDmitriy

Bugfixes on tickets:
#282
#343
#346
#283
#275
#304
#285
#255
#344

2023-12-22 11:26 UTC, DenysLiubchenko requested changes

2023-12-22 11:26 UTC, DenysLiubchenko commented on service-api/src/main/java/greencity/dto/user/UserManagementViewDto.java
>      private String email;
Validate email

2023-12-22 11:27 UTC, DenysLiubchenko commented
And I think something is wrong with [#344](https://github.com/OlhenShu/GreenCityProjectStage/issues/344) task. Maby you need to sign in as User?

2023-12-22 11:34 UTC, DenysLiubchenko commented on service-api/src/main/java/greencity/dto/user/UserManagementViewDto.java
>      private String email;
Also you need to remove blank line at start of block because of checkstyle

2023-12-22 12:11 UTC, KizerovDmitriy commented
> And I think something is wrong with [#344](https://github.com/OlhenShu/GreenCityProjectStage/issues/344) task. Maybe you need to sign in as User?

Maybe you're right, I'll redo it. Thank you.

2023-12-26 10:59 UTC, DenysLiubchenko approved these changes

2023-12-26 11:00 UTC, lagysha approved these changes
Nice

2024-01-10 10:32 UTC, merged