237 POST /email/sendUserViolation fix status code if invalid email
OlhenShu/GreenCityUserMVPTemplate pull request #18
Opened 2023-12-24 15:30 UTC by Rafaelkaaa

https://github.com/OlhenShu/GreenCityProjectStage/issues/237

2023-12-27 13:20 UTC, urio999 approved these changes
Well Done

2024-01-10 09:30 UTC, DenysLiubchenko requested changes

2024-01-10 09:30 UTC, DenysLiubchenko commented on core/src/main/java/greencity/controller/EmailController.java
> +            @ApiResponse(code = 404, message = HttpStatuses.NOT_FOUND),
You need to delete coma here

2024-01-10 09:30 UTC, DenysLiubchenko commented on core/src/main/java/greencity/config/SecurityConfig.java
> +                "/email/sendUserViolation")
Here you need to alter ')' into ','

2024-01-10 09:32 UTC, lagysha commented on service/src/main/java/greencity/service/EmailServiceImpl.java
> +        if(!dto.getEmail().matches("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$")){
You can use on dto field @Email annotation instead of validating here

2024-01-13 12:17 UTC, merged